### ISSUE TITLE
Fileflows hangs and leak memory when starting a new scan

### ISSUE THREAD

**Issue by SergiX44** [revenz/FileFlows#136]
Version 0.8.2

After started the scan on a quite big library, fileflows start spitting errors and takes something like 2-3GB of RAM.

If you try to restart the service, fileflows crashes in an uninterruptible IO wait, and you need to restart the machine:
![image](https://user-images.githubusercontent.com/4172890/174899534-3c7b67d6-b77f-4207-a93b-321fb2453d14.png)

Part of the logs after clicked rescan:
```
Jun 21 23:15:03 home-srv FileFlows[2069]: Error -> Error in queue: One or more errors occurred. (Collection was modified; enumeration operation may not execute.)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task`1.get_Result()
Jun 21 23:15:03 home-srv FileFlows[2069]:    at FileFlows.Server.Workers.WatchedLibrary.ProcessQueuedItem()
Jun 21 23:15:03 home-srv FileFlows[2069]: 2022-06-21 23:15:03.508 [ERRR] -> Error in queue: One or more errors occurred. (Collection was modified; enumeration operation may not execute.)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task`1.get_Result()
Jun 21 23:15:03 home-srv FileFlows[2069]:    at FileFlows.Server.Workers.WatchedLibrary.ProcessQueuedItem()
Jun 21 23:15:03 home-srv FileFlows[2069]: Error -> Error in queue: One or more errors occurred. (Collection was modified; enumeration operation may not execute.)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task`1.get_Result()
Jun 21 23:15:03 home-srv FileFlows[2069]:    at FileFlows.Server.Workers.WatchedLibrary.ProcessQueuedItem()
Jun 21 23:15:03 home-srv FileFlows[2069]: 2022-06-21 23:15:03.509 [ERRR] -> Error in queue: One or more errors occurred. (Collection was modified; enumeration operation may not execute.)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task`1.get_Result()
Jun 21 23:15:03 home-srv FileFlows[2069]:    at FileFlows.Server.Workers.WatchedLibrary.ProcessQueuedItem()
Jun 21 23:15:03 home-srv FileFlows[2069]: Error -> Error in queue: One or more errors occurred. (Collection was modified; enumeration operation may not execute.)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task`1.get_Result()
Jun 21 23:15:03 home-srv FileFlows[2069]:    at FileFlows.Server.Workers.WatchedLibrary.ProcessQueuedItem()
Jun 21 23:15:03 home-srv FileFlows[2069]: 2022-06-21 23:15:03.509 [ERRR] -> Error in queue: One or more errors occurred. (Collection was modified; enumeration operation may not execute.)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
Jun 21 23:15:03 home-srv FileFlows[2069]:    at System.Threading.Tasks.Task`1.get_Result()
Jun 21 23:15:03 home-srv FileFlows[2069]:    at FileFlows.Server.Workers.WatchedLibrary.ProcessQueuedItem()
Jun 21 23:15:04 home-srv FileFlows[2069]: Info -> Triggering worker: FlowRunnerMonitor
Jun 21 23:15:04 home-srv FileFlows[2069]: 2022-06-21 23:15:04.509 [INFO] -> Triggering worker: FlowRunnerMonitor
Jun 21 23:15:04 home-srv FileFlows[2069]: 2022-06-21 23:15:04.985 [INFO] -> Processing Timer Queue: tv-series
Jun 21 23:15:04 home-srv FileFlows[2069]: Info -> Processing Timer Queue: tv-series
Jun 21 23:15:04 home-srv FileFlows[2069]: 2022-06-21 23:15:04.985 [INFO] -> Processing Timer Queue: tv-series
Jun 21 23:15:04 home-srv FileFlows[2069]: Info -> Processing Timer Queue: tv-series
Jun 21 23:15:04 home-srv FileFlows[2069]: 2022-06-21 23:15:04.985 [INFO] -> Processing Timer Queue: tv-series
Jun 21 23:15:04 home-srv FileFlows[2069]: Info -> Processing Timer Queue: tv-series
Jun 21 23:15:07 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:07 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:07 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:07 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:07 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:07 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:07 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:07 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:07 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:08 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:09 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:09 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:09 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:09 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:09 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:09 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:09 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:09 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:09 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:09 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:10 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
Jun 21 23:15:11 home-srv dotnet[2069]: SQLite error (5): database is locked in "update DbObject set DateModified = @0 where Uid = @1"
```

**Comment by revenz** [comment]
sorry my linux isnt super strong, does the first screenshot show many instances of the node running, or is it a time lapse with different instances that were started/stopped?

also tried using docker?

**Comment by SergiX44** [comment]
I've a systemd unit that manage fileflows, the first screen show the processes stuck in the D state, which states for this: https://en.wikipedia.org/wiki/Sleep_(system_call)#Uninterruptible_sleep

The only way to get rid of that is to restart the machine.

I think is the main issue is that you are trying to use sqlite with multiple wirte connections, so they ends up in deadlock waiting for the lock to release: https://sqlite.org/faq.html#q5

**Comment by revenz** [comment]
the library scan does one file at a time, doesnt insert heaps in parallel.   I'm leaning towards environmental otherwise everyone would be experiencing this.

so to rule some things out.
try running the server normally from terminal, and not via systemd

**Comment by SergiX44** [comment]
Tested with a docker image and also launching via shell, same result.

Maybe the scan is doing only one file at a time, but the log is clear that the sqlite driver is complaining about a lock when firing those updated 🤔

**Comment by revenz** [comment]
k, can you attach your actual fileflows server log and ill take a look

**Comment by SergiX44** [comment]
[FileFlows-Jun21-01.txt](https://github.com/revenz/FileFlows/files/8958370/FileFlows-Jun21-01.txt)

**Comment by revenz** [comment]
think i fixed these now.  check in 0.8.3 when thats released.  leaving this open for confirmation

**Comment by SergiX44** [comment]
Thanks!

**Comment by revenz** [comment]
check 0.8.3

**Comment by SergiX44** [comment]
Updated to the latest version:

🔝 Fileflows stopped leaking memory or going in a io deadlock state like on the 0.8.2
😢 The library scan still throws errors and is not adding file to the library queue

Error logs:
```
2022-06-26 10:19:22.964 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E07 - Point Of No Return.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.099 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E07 - Point Of No Return.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E07 - Point Of No Return.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.100 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E07 - Point Of No Return.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.103 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: Info -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E08 - Love Is a Battlefield.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.241 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E08 - Love Is a Battlefield.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E08 - Love Is a Battlefield.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.242 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E08 - Love Is a Battlefield.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Info -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.244 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E09 - The Getaway.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.339 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E09 - The Getaway.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E09 - The Getaway.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.340 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E09 - The Getaway.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.343 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: Info -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E10 - Means To An End.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.492 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E10 - Means To An End.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E10 - Means To An End.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.494 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E10 - Means To An End.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.495 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: Info -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.596 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E11 - Meet The New Beast.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E11 - Meet The New Beast.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.596 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E11 - Meet The New Beast.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E11 - Meet The New Beast.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Info -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.600 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E12 - No Way Out.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E12 - No Way Out.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.737 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E12 - No Way Out.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.737 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E12 - No Way Out.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.739 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: Info -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.882 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E13 - Au Revoir.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E13 - Au Revoir.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E13 - Au Revoir.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.882 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Beauty and the Beast/Season 04/Beauty and the Beast - S04E13 - Au Revoir.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.883 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: Info -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 02/Better Call Saul - S02E02 - La Torta della Luna Piena.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.993 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 02/Better Call Saul - S02E02 - La Torta della Luna Piena.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 02/Better Call Saul - S02E02 - La Torta della Luna Piena.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.993 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 02/Better Call Saul - S02E02 - La Torta della Luna Piena.mkv
Jun 26 10:19:23 home-srv FileFlows[22206]: Info -> Processing Timer Queue: tv-series
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.995 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:24 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E01 - Vino e rose.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.136 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E01 - Vino e rose.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.136 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E01 - Vino e rose.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E01 - Vino e rose.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: Info -> Processing Timer Queue: tv-series
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.139 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:24 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E02 - La carota e il bastone.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.238 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E02 - La carota e il bastone.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E02 - La carota e il bastone.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.239 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E02 - La carota e il bastone.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.244 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:24 home-srv FileFlows[22206]: Info -> Processing Timer Queue: tv-series
Jun 26 10:19:24 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E03 - Tra l'incudine e il martello.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.385 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E03 - Tra l'incudine e il martello.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E03 - Tra l'incudine e il martello.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.386 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E03 - Tra l'incudine e il martello.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.387 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:24 home-srv FileFlows[22206]: Info -> Processing Timer Queue: tv-series
Jun 26 10:19:24 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E04 - Pirata della strada.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.488 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E04 - Pirata della strada.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.488 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E04 - Pirata della strada.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E04 - Pirata della strada.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: Info -> Processing Timer Queue: tv-series
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.491 [INFO] -> Processing Timer Queue: tv-series
Jun 26 10:19:24 home-srv FileFlows[22206]: Debug -> New unknown file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E05 - Nero e blu.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.617 [DBUG] -> New unknown file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E05 - Nero e blu.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: Debug -> Cannot access file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E05 - Nero e blu.mkv
Jun 26 10:19:24 home-srv FileFlows[22206]: 2022-06-26 10:19:24.617 [DBUG] -> Cannot access file: /mnt/plex-gdrive/tv-series/Better Call Saul (2015)/Season 06/Better Call Saul - S06E05 - Nero e blu.mkv
```

The server disk mount is `read-only` if that can help (is using the plexdrive fuse mout) and the nodes have obv the full rw access mount, so in this config, the server is only doing the orchestration of the nodes, and not doing any actual work.


Its now also throwing this error often:
```
Jun 26 10:19:23 home-srv FileFlows[22206]: Error -> Error in worker 'SystemMonitor': Object reference not set to an instance of an object.
Jun 26 10:19:23 home-srv FileFlows[22206]:    at FileFlows.Server.Workers.SystemMonitor.Execute()
Jun 26 10:19:23 home-srv FileFlows[22206]:    at FileFlows.ServerShared.Workers.Worker.<Trigger>b__17_0()
Jun 26 10:19:23 home-srv FileFlows[22206]: 2022-06-26 10:19:23.180 [ERRR] -> Error in worker 'SystemMonitor': Object reference not set to an instance of an object.
Jun 26 10:19:23 home-srv FileFlows[22206]:    at FileFlows.Server.Workers.SystemMonitor.Execute()
Jun 26 10:19:23 home-srv FileFlows[22206]:    at FileFlows.ServerShared.Workers.Worker.<Trigger>b__17_0()
```
But I think is not related to the library issue but to the new system page feature

**Comment by revenz** [comment]
yeah it needs write access to the file, this is because most people just use "Replace Original"

**Comment by SergiX44** [comment]
> yeah it needs write access to the file, this is because most people just use "Replace Original"

No the server does not need this. Its internal node is disabled and should not edit any files, it should read them and add them to the libraries. Instead, the other nodes do the work have their own mount that has read and write of course.

BUT, the server still gives those errors put in the previous message saying it can't access the file. I checked the permissions and it can read metadata, list and read the files itself, that would seem to be the problem.

Why would the scan open the files for writing?

Translated with www.DeepL.com/Translator (free version)

**Comment by revenz** [comment]
because most users are using the internal node and to simplify things, when adding to the library it checks if it can open for writing.

**Comment by revenz** [comment]
![image](https://user-images.githubusercontent.com/958400/175807636-3d456726-f1e2-4b52-9d13-c37daea7a02f.png)

added this to the next version which will skip these tests.

Might do a 0.8.4 release during the week, if not next weekend.
